In [2]:
from tensorflow import keras

(x_train, _), (x_test, _) = keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [19]:
import numpy as np

a = np.zeros((0, 44100), dtype=np.int16)

b = np.zeros((1, 44100), dtype=np.int16)

np.vstack((a, b)).shape

(1, 44100)

In [24]:
print(x_train.shape)

(60000, 28, 28)


In [39]:
a = np.array([[1,2,3], [100,200,300], [10000,20000,30000], [10, 20, 30]])

In [40]:
np.random.shuffle(a)
a

array([[    1,     2,     3],
       [10000, 20000, 30000],
       [  100,   200,   300],
       [   10,    20,    30]])

In [41]:
a.shape

(4, 3)

In [42]:
np.iinfo(np.int16).max

32767

In [1]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8427021741583746132
 xla_global_id: -1]

In [3]:
!pip install scipy
import scipy.io.wavfile

     |████████████████████████████████| 34.5 MB 14.8 MB/s eta 0:00:01   |███                             | 3.3 MB 9.8 MB/s eta 0:00:04     |████████████████████████▋       | 26.6 MB 16.0 MB/s eta 0:00:01
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [4]:
files = ["../data/wav44100/3DEmbodimentFromLines.wav"]

In [8]:
a = scipy.io.wavfile.read(files[0])[1]

In [9]:
import numpy as np

In [10]:
a

array([-21, -18, -16, ...,   2,   0,   0], dtype=int16)

In [11]:
fft = np.fft.fft(a[0:4410])

In [12]:
fft

array([-10465.           +0.j        ,  -9365.13188876 -619.70977957j,
       -11125.21676878-1785.4665945j , ...,
       -11218.34021479+3831.69134105j, -11125.21676878+1785.4665945j ,
        -9365.13188876 +619.70977957j])

In [13]:
b = np.fft.ifft(fft)

In [14]:
b

array([-21.+4.97863277e-15j, -18.+2.88889598e-14j, -16.-3.58307481e-15j,
       ..., 104.-4.86794344e-14j, 107.-5.74810487e-14j,
       110.-7.17008656e-14j])

In [17]:
scipy.io.wavfile.write("a.wav", 44100, a[0:4410])
scipy.io.wavfile.write("b.wav", 44100, b.real)

In [27]:
indices = np.argpartition(-np.abs(fft), 16)[:16]
c = np.where(np.abs(fft) >= np.abs(fft)[indices[15]], fft, 0)

In [29]:
d = np.fft.ifft(c)

In [30]:
d

array([80.44285834-1.15491391e-14j, 87.348809  -1.48488931e-14j,
       94.36922426+0.00000000e+00j, ..., 61.71049416-4.17391920e-14j,
       67.49978169-5.62163843e-14j, 73.78401635-7.01909944e-15j])

In [31]:

scipy.io.wavfile.write("d.wav", 44100, d.real)

In [61]:
amps = np.absolute(c)
amps

array([0., 0., 0., ..., 0., 0., 0.])

In [62]:
import cmath
to_phase = np.vectorize(lambda x: cmath.phase(x))
phases = to_phase(c)
phases

array([0., 0., 0., ..., 0., 0., 0.])

In [65]:
e = amps * np.exp(phases * 1j)
e

array([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j])

In [66]:
f = scipy.fft.ifft(e)
scipy.io.wavfile.write("f.wav", 44100, f.real)

In [71]:
out = np.zeros((0,), dtype=np.int16)
for i in range(0, 44100, 4410):
    fft = np.fft.fft(a[i:i+4410])
    ifft = np.fft.ifft(fft)
    out = np.hstack((out, ifft.real))

scipy.io.wavfile.write("test.wav", 44100, out)

In [72]:
amps.shape

(4410,)

In [73]:
phases.shape

(4410,)

In [1]:
import numpy as np
a = np.arange(1024)
a.shape

(1024,)

In [2]:
np.fft.fft(a).shape

(1024,)

In [3]:
import numpy as np
a = np.array([0.1, 0.2, 0.3])

In [4]:
np.max(a)

0.3

In [10]:
a = np.zeros((0, ), dtype=np.int16)

In [14]:
a = np.hstack((a, np.array([1, 2, 3])))
a = np.hstack((a, np.array([1, 2, 3])))

In [15]:
a

array([1, 2, 3, 1, 2, 3])

In [38]:
import numpy as np
a = np.array([[[0, 0, 0, 0], [1, 1, 1, 1]], [[2, 2, 2, 2], [3, 3, 3, 3]], [[0, 0, 0, 0], [4, 4, 4, 4]]])

In [39]:
a

array([[[0, 0, 0, 0],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 0, 0, 0],
        [4, 4, 4, 4]]])

In [40]:
a[:,0,:]

array([[0, 0, 0, 0],
       [2, 2, 2, 2],
       [0, 0, 0, 0]])

In [41]:
np.sum(a[:,0,:], axis=1)

array([0, 8, 0])

In [42]:
np.where(np.sum(a[:,0,:], axis=1) < 0.1)

(array([0, 2]),)

In [45]:
np.delete(a, np.where(np.sum(a[:,0,:], axis=1) < 0.1)[0], axis=0)

array([[[2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [19]:
import numpy as np

a = np.array([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], [[1200, 100, 200, 300], [400, 500, 600, 700], [800, 900, 1000, 1100]], [[120000, 10000, 20000, 30000], [40000, 50000, 60000, 70000], [80000, 90000, 100000, 110000] ]])
b = np.array([[-1, -2, -3], [-100, -200, -300]])

print(a.shape)
np.concatenate([a[:-1, :, :], a[1:, 0, :].reshape(a.shape[0] - 1, 1, a.shape[2])], 1)

(3, 3, 4)


array([[[     0,      1,      2,      3],
        [     4,      5,      6,      7],
        [     8,      9,     10,     11],
        [  1200,    100,    200,    300]],

       [[  1200,    100,    200,    300],
        [   400,    500,    600,    700],
        [   800,    900,   1000,   1100],
        [120000,  10000,  20000,  30000]]])